# -*- coding: utf-8 -*-
"""Tugas 2 - KapStat - Kelompok 10 Butuh Libur.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E5bqIZVk5qphkkwex2LjvFghWvAZBSzD

**Tugas 2 - Kelompok 10 - Butuh Libur**

*   6161901066 - Dennis Imanuel
*   6161901104 - Putu Lila Kusumayani
*   6161901114 - Bilqis Aulia R.
*   6161901116 - Tiara Alamanda

-------------------------------------
Dataset yang digunakan adalah data "Jumlah Balita (12 - 59 Bulan) Berdasarkan Jenis Kelamin di Jawa Barat" yang berasal dari sumber URL:
https://opendata.jabarprov.go.id/id/dataset/jumlah-balita-12---59-bulan-berdasarkan-jenis-kelamin-di-jawa-barat

# Data Extraction
"""

# Instalasi pyspark
!pip install pyspark

# import library yang digunakan
import pandas as pd
import matplotlib.pyplot as plt
import requests
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, FloatType, IntegerType
from pyspark.sql.functions import avg, min, max, stddev, desc

# Membuat spark session
spark = SparkSession.builder.appName("Analisis Jumlah Balita Jabar").getOrCreate()

# Mengambil data dari api
response = requests.get("https://data.jabarprov.go.id/api-backend/bigdata/dinkes/od_19880_jumlah_balita_12__59_bulan_berdasarkan_jenis_kelamin")

# Melakukan proses extract
#data = response.json()['features']
data = response.json()["data"]
print(data)

df = spark.createDataFrame(data)
df.show()

"""# Data Analysis dengan SPARK SQL"""

df.createOrReplaceTempView("data_balita")

"""### 1. Hubungan Jumlah Balita dengan Tahun"""

result1 = spark.sql("""
  SELECT
    tahun, SUM(jumlah_balita) AS Jumlah_Balita
  FROM data_balita
  GROUP BY tahun
"""
)
result1.show()

result_pd1 = result1.toPandas()
result_pd1.plot(kind = "bar", x = "tahun", y = "Jumlah_Balita", color = "purple", alpha = 1)
plt.xlabel("Tahun")
plt.ylabel("Jumlah Balita")
plt.title("Jumlah Balita Tahun 2019 dan 2020")
plt.grid(True)
plt.gca().get_yaxis().get_major_formatter().set_scientific(False)

plt.show()

"""### 2. Perbandingan Jumlah Balita Laki-Laki dan Perempuan"""

result2 = spark.sql("""
  SELECT
    jenis_kelamin,
    SUM(jumlah_balita) AS Jumlah_Balita
  FROM data_balita
  GROUP BY jenis_kelamin
"""
)
result2.show()

#Pie chart untuk Perbandingan Balita Laki-Laki dan Perempuan
result_pd2 = result2.toPandas()
ax = result_pd2.plot(kind = "pie", y = "Jumlah_Balita", labels=result_pd2['jenis_kelamin'], autopct='%1.1f%%', title='Perbandingan Jenis Kelamin Balita di Jawa Barat', colors=['lightblue','salmon'], explode=[0, 0])
ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))

"""### 3. Top 10 Kabupaten/Kota dengan jumlah balita terbanyak/paling sedikit

"""

result3 = spark.sql("""
  SELECT
    nama_kabupaten_kota,
    SUM(jumlah_balita) AS Jumlah
  FROM data_balita
  GROUP BY nama_kabupaten_kota
  ORDER BY Jumlah DESC
  Limit 10
"""
)
result3.show()

#Bar chart untuk 10 Kabupaten/Kota dengan Jumlah Balita Terbanyak
result_pd3 = result3.toPandas()
result_pd3.plot(kind = "barh", x = "nama_kabupaten_kota", y = "Jumlah", color = "teal", alpha = 1)
plt.xlabel("Jumlah Balita")
plt.ylabel("Kabupaten / Kota")
plt.title("Top 10 Kabupaten / Kota di Jawa Barat dengan Jumlah Balita Terbanyak")
plt.grid(True)
plt.show()

result4 = spark.sql("""
  SELECT
    nama_kabupaten_kota,
    SUM(jumlah_balita) AS Jumlah
  FROM data_balita
  GROUP BY nama_kabupaten_kota
  ORDER BY Jumlah ASC
  Limit 10
"""
)
result4.show()

#Bar chart untuk 10 Kabupaten/Kota dengan Jumlah Balita Paling Sedikit
result_pd4 = result4.toPandas()
result_pd4.plot(kind = "barh", x = "nama_kabupaten_kota", y = "Jumlah", color = "teal", alpha = 1)
plt.xlabel("Jumlah Balita")
plt.ylabel("Kabupaten / Kota")
plt.title("Top 10 Kabupaten / Kota di Jawa Barat dengan Jumlah Balita Paling Sedikit")
plt.grid(True)
plt.show()

"""### 4. Selisih antara jumlah balita laki-laki dengan balita perempuan pada masing-masing Kabupaten/Kota

"""

result34 = spark.sql("""
SELECT
  nama_kabupaten_kota,
  SUM(CASE WHEN jenis_kelamin = 'LAKI-LAKI' THEN jumlah_balita ELSE 0 END) AS Jumlah_LakiLaki,
  SUM(CASE WHEN jenis_kelamin = 'PEREMPUAN' THEN jumlah_balita ELSE 0 END) AS Jumlah_Perempuan,
  SUM(CASE WHEN jenis_kelamin = 'LAKI-LAKI' THEN jumlah_balita ELSE 0 END) - SUM(CASE WHEN jenis_kelamin = 'PEREMPUAN' THEN jumlah_balita ELSE 0 END) AS Selisih
FROM data_balita
GROUP BY nama_kabupaten_kota
ORDER BY Jumlah_LakiLaki DESC;
"""
)
result34.show()

result_pd34 = result34.toPandas()
result_pd34.plot(kind = "barh", x = "nama_kabupaten_kota", y = "Selisih", color = "cyan", alpha = 1)
plt.xlabel("Selisih Jumlah Balita Laki-Laki dengan Perempuan")
plt.ylabel("Kabupaten / Kota")
plt.title("Selisih antara jumlah balita laki-laki dengan balita perempuan pada masing-masing Kabupaten/Kota")
plt.grid(True)

plt.show()

"""### 5. Persentase perubahan jumlah balita pada masing-masing Kabupaten/Kota antar tahun 2019 ke 2020"""

result5 = spark.sql("""
SELECT
  nama_kabupaten_kota,
  SUM(CASE WHEN tahun = '2019' THEN jumlah_balita ELSE 0 END) AS Tahun_2019,
  SUM(CASE WHEN tahun = '2020' THEN jumlah_balita ELSE 0 END) AS Tahun_2020,
  ((SUM(CASE WHEN tahun = '2020' THEN jumlah_balita ELSE 0 END) - SUM(CASE WHEN tahun = '2019' THEN jumlah_balita ELSE 0 END)) / SUM(CASE WHEN tahun = '2019' THEN jumlah_balita ELSE 0 END)) * 100 AS Persentase_Perubahan
FROM data_balita
GROUP BY nama_kabupaten_kota
"""
)
result5.show()
#SUM(CASE WHEN tahun = '2021' THEN jumlah_balita ELSE 0 END) AS Tahun_2021,

